### ISSUE TITLE
`npm i` fails when canvas-webp is installed before canvas

### ISSUE THREAD

**Issue by winstxnhdw** [zbjornson/node-canvas-webp#5]
# How to reproduce

Use this package.json

```js
{
  "dependencies": {
    "canvas": "^2.10.1",
    "canvas-webp": "^1.0.0",
  },
}
```
Then
```sh
npm i
```

**Comment by zbjornson** [comment]
Unfortunately I haven't tried to use this package in years and won't have time to look at this for a while.

Newer versions of node-canvas support `canvas.toBuffer("raw")`. The Buffer returned by that can be efficiently passed to `WebPEncode{Lossless}BGRA()` (from libwebp) if you can find another Node.js module that exposes that API.

**Comment by winstxnhdw** [comment]
Might try that one day. Currently, I'll just add this repository as a submodule, then add a post install script to rebuild node-gyp. Thanks for the help :)

EDIT: Nevermind. Switching over to https://github.com/Brooooooklyn/canvas. It'll be better than whatever I could ever write right now.
